Issue #51: plugin crash with java.lang.NoSuchMethodError
- Fix an incompatibility with version 13.x due to an API method removal.
- Due to the API change, the minimum supported version is now IDEA 13.